### ISSUE TITLE
Creating Transaction without Blockr

### ISSUE THREAD

**Issue by kyluke** [utamaro/gocoin#1]
Hey man, great libary!

Quick question, do you have a version or an example on how to create a transaction without Blockr? I'm writing something which will already know what the input transaction hash will be. So it doesn't need to get another list of unspent transactions.

Any ideas?

Thanks a mil.

**Comment by utamaro** [comment]
Unfortunately there is no expamle.

But you can see the final tx data(rawtx) in  [Pay function](https://github.com/utamaro/gocoin/blob/master/p2pkh.go#L146), so I believe it's easy to implement custom [service](https://github.com/utamaro/gocoin/blob/master/service.go#L54) and modify the func as you wish.

Maybe I'll add the func which returns rawtx when I have time :)

**Comment by utamaro** [comment]
I splited gocoin into 3 parts(address/transaction/sending).

https://github.com/bitgoin

You could use tx package by making own UTXO struct for your purpose.
https://github.com/bitgoin/tx
